### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by gorhgorh** [trainyard/choo-cli#105]
### Expected behavior
when i ```npm install -g choo-cli``` i expect choo-cli to be installed

### Actual behavior
it errors with the following message during the pre install script

```
/Users/gorhgorh/.nvm/versions/node/v7.3.0/bin/choo -> /Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/bin/cli.js
/Users/gorhgorh/.nvm/versions/node/v7.3.0/bin/choo-new -> /Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/bin/choo-new.js
/Users/gorhgorh/.nvm/versions/node/v7.3.0/bin/choo-generate -> /Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/bin/choo-generate.js

> nodegit@0.16.0 install /Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl' }
/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl' }
/Users/gorhgorh/.nvm/versions/node/v7.3.0/lib
└── (empty)
```

### Steps to reproduce behavior
 ```npm install -g choo-cli``` on my mac.
osx : 10.12.4
node : v7.3.0 (tried on 7.10 too)

full npm log [here](https://gist.github.com/gorhgorh/4a86b9265890181f3bae99ff1cf5be59)

**Comment by IzumiSy** [comment]
You can see this issue to get a clue: https://github.com/nodegit/nodegit/issues/1156
