### ISSUE TITLE
Installation error related to libssh2

### ISSUE THREAD

**Issue by IzumiSy** [trainyard/choo-cli#114]
### Expected behavior
choo-cli successfully gets installed

### Actual behavior
In installation process, `npm install -g choo-cli` puts this error log.
```
izumisy@Seiya-no-MacBook-Air:~/devs
 $ npm install -g choo-cli
/Users/izumisy/.nvm/versions/node/v6.5.0/bin/choo-new -> /Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/bin/choo-new.js
/Users/izumisy/.nvm/versions/node/v6.5.0/bin/choo-generate -> /Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/bin/choo-generate.js
/Users/izumisy/.nvm/versions/node/v6.5.0/bin/choo -> /Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/bin/cli.js

> nodegit@0.16.0 install /Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
  killed: false,
  code: 77,
  signal: null,
  cmd: '/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl' }
/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
  killed: false,
  code: 77,
  signal: null,
  cmd: '/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/izumisy/.nvm/versions/node/v6.5.0/lib/node_modules/choo-cli/node_modules/nodegit/vendor/openssl/openssl' }
/Users/izumisy/.nvm/versions/node/v6.5.0/lib
└── (empty)
```

### Steps to reproduce behavior
Just run `npm install -g choo-cli`
My environment is Node 6.5.0 with npm 3.10.3 on OSX El Capitan 10.11.6

**Comment by MattMcFarland** [comment]
Hi, this appears to be an issue with nodegit. [They appear to have a lot of issues with libssh2 ](https://github.com/nodegit/nodegit/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20libssh2)

We might consider moving away from nodegit and using regular http for git stuff.  Are you behind a proxy at all?
