### ISSUE TITLE
Generators fail to generate templates in windows

### ISSUE THREAD

**Issue by rollymaduk** [trainyard/choo-cli#35]
### Expected behavior

Generator should generate corresponding templates in commandline 
`choo generate page newpage`  or
`choo generate element newElement`
should trigger generator build
### Actual behavior

generator fails to generate templates but rather it throws an error in windows console. 

```
C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\bin\choo-generate.js:36
  throw e
  ^
AssertionError: Trying to copy from a source that does not exist: C:\Users\rolly_000\WebstormProjects\CWCSProject\client\elements\C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli
\generators\element\template.js
    at EditionInterface.exports._copySingle (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\mem-fs-editor\lib\actions\copy.js:45:3)
    at EditionInterface.exports.copy (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)
    at EditionInterface.module.exports [as move] (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\mem-fs-editor\lib\actions\move.js:4:8)
    at mv (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\utils.js:35:28)
    at generate (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\utils.js:38:3)
    at Object.module.exports [as element] (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\generators\element\index.js:8:3)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\bin\choo-generate.js:33:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\exec.js:10
      throw new Error('Error code: ' + code)
      ^

Error: Error code: 1
    at ChildProcess.exec.on.code (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\exec.js:10:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```
### Steps to reproduce behavior

enter choo generate command in command line e.g
`choo generate page newPage`

**Comment by YerkoPalma** [comment]
Where are you step in the command line? in `C:\Users\rolly_000\WebstormProjects\CWCSProject` or in `C:\Users\rolly_000\WebstormProjects\CWCSProject\client\elements` ?

**Comment by rollymaduk** [comment]
C:\Users\rolly_000\WebstormProjects\CWCSProject\client

**Comment by rollymaduk** [comment]
hello @YerkoPalma, did you find anything that might help me resolve this issue? I will appreciate your help on this thanks.

**Comment by YerkoPalma** [comment]
Hi @rollymaduk, I guess I found the problem. Here this line

```
C:\Users\rolly_000\WebstormProjects\CWCSProject\client\elements\C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli
\generators\element\template.js
```

That line is weird to me for two reasons.
- It seems that node `path.resolve` function is taking a full path when we expect a relative path.
- The last part `C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli
  \generators\element\template.js` should be more like this `C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli
  \generators\element\template\element.js` there might be a problem with [this line](https://github.com/trainyard/choo-cli/blob/master/lib/utils.js#L38) affecting only the default generators.

Now is strage that this haven't been spoted in any test, we might also have to improve them.
In the mean time, I have no time to check deeper, so If you want you could check the two options that I mentioned above, and if you find a solution submit a PR. If not, I will check it in a couple of days :smile:
